modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "mekanismbridge"
version = "1.0"
displayName = "mekanismbridge"
authors = "Raikin"
description = '''a mod for bridging chemlib and mekanism!'''

[[dependencies.mekanismbridge]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.mekanismbridge]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.mekanismbridge]]
modId = "mekanism"
mandatory=true
versionRange="[1.19.2-10.3.9.13,)"
ordering="NONE"
side="BOTH"

[[dependencies.mekanismbridge]]
modId="alchemistry"
mandatory=true
versionRange="[1.19.2-2.3.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.mekanismbridge]]
modId="alchemylib"
mandatory=true
versionRange="[1.19.2-1.0.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.mekanismbridge]]
modId="chemlib"
mandatory=true
versionRange="[1.19.2-2.0.17,)"
ordering="NONE"
side="BOTH"