modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "mekanismbridge"
version = "2.2"
displayName = "mekanismbridge"
authors = "Raikin"
description = '''a mod for bridging chemlib and mekanism!'''

[[dependencies.mekanismbridge]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.mekanismbridge]]
modId = "minecraft"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

